### ISSUE TITLE
while keyword is not highlighted and other keyword issues

### ISSUE THREAD

**Issue by RecruitMain707** [TiePy/nimatron#10]
while is simple not highlighted, no errors are thrown, the fix should be easy, however, there are certain functions of the system that are highlighted as keywords, and (i think) they shouldnt, either highlight them with another color, for all the functions, or dont highlight them at all.

And related to this, pop (one of this) functions is also highlighted when its actually a pragma:

![image](https://user-images.githubusercontent.com/37117366/90824583-eac97880-e337-11ea-9620-3aeaa9b22046.png)

**Comment by stever** [comment]
There is currently a colour settings page which allows procedure colours to be altered. There is a list of built-in procedures that are highlighted as procedures. The default setting for keyword and procedure name are the same.

At the moment the built-in functions are highlighted by the lexer, which seems undesirable here. I can remove this and work on providing highlighting via work to be done later.

**Comment by stever** [comment]
On a related note, I've been wondering about the following operators: in|notin|is|isnot|not|of|as. The one operator here that I really want to be a keyword is 'of'. In the Nim grammar specification these are operators and keywords.

**Comment by stever** [comment]
As of today, Nimatron is obsolete following the release of a JetBrains plugin for Nim. This issue will be closed, and the Nimatron repository will be archived. I recommend the new JetBrains plugin.
