### ISSUE TITLE
syntax doesnt consider multiline arguments correct

### ISSUE THREAD

**Issue by RecruitMain707** [TiePy/nimatron#4]
![image](https://user-images.githubusercontent.com/37117366/90271345-f3afdb00-de5b-11ea-9462-79398e379cda.png)

This is easier to explain with a picture, luckily it doesnt output weird token errors.

**Comment by RecruitMain707** [comment]
Also, regarding the last fix you did about assigning number types with an apostrophe, you forgot to add the other possiblities, (i32, i16, i8, f32, etc...)

the full list is here:
https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants
(scroll a bit down and you will find a table with all of them)

**Comment by stever** [comment]
I've re-opened the other issue. I'll take another look, and sort those too.

**Comment by stever** [comment]
I have a fix for this which ignores indentation while parsing routine arguments. This will be included in the next release.
